// Complete menu seed data for Ziba Beach Resort
export const COMPLETE_MENU_SEED = [
  {
    id: "breakfast-001",
    name: "Breakfast",
    timing: "7:00 AM – 10:00 AM DAILY",
    note: "THIS À LA CARTE MENU IS AVAILABLE ON DAYS, BUFFET IS NOT OFFERED.",
    isActive: true,
    items: [
      {
        id: "bf-001",
        name: "Toast Bread",
        description:
          "Toast bread and omelette served with choice of Tea/Coffee/Hot chocolate",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "bf-002",
        name: "Full English Breakfast",
        description:
          "Bread Basket, Baked beans, Steamed carrots, potatoes, Grilled sausage, Eggs your way, choice of Oatmeal|Cornflakes|Custard and choice of Tea|Coffee|Hot Chocolate",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "bf-003",
        name: "American Breakfast",
        description:
          "Pancakes, Potatoes served with Bacon or sausage, Eggs your way and choice of Tea|Coffee|Hot Chocolate",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "bf-004",
        name: "Tubers 'N' Sauces",
        description:
          "Boiled or fried Yam served with your choice of Egg Sauce/Fish Sauce/Vegetable Sauce",
        priceNGN: 8300,
        isActive: true,
      },
      {
        id: "bf-005",
        name: "Plantain n Vegetable Sauce",
        description:
          "Plantain how you like it [Boiled, fried or grilled with Ziba vegetable sauce.",
        priceNGN: 8300,
        isActive: true,
      },
      {
        id: "bf-006",
        name: "Naija Breakfast",
        description: "Akara & Pap",
        priceNGN: 8500,
        isActive: true,
      },
      {
        id: "bf-007",
        name: "Oat Bowl",
        description:
          "Served with boiled Eggs,Nuts,Coconut flakes,Honey and dates.",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "bf-008",
        name: "Yoghurt Bowl",
        description:
          "Greek Yoghurt served with granola, chia seeds, coconut flakes and fruit of choice",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "bf-009",
        name: "French Toast",
        description:
          "Served with Egg, cinnamon powder, sausage and baked beans.",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "bf-010",
        name: "Yamarita Special",
        description: "Served with Vegetable or Fish sauce",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "bf-011",
        name: "Potato Fiesta",
        description:
          "Grilled or Fried sweet Potato served with Egg or Fish sauce",
        priceNGN: 9300,
        isActive: true,
      },
      {
        id: "bf-012",
        name: "Plain Homemade Pancake",
        description: "Served with syrup, scrambled eggs and sausage",
        priceNGN: 7750,
        isActive: true,
      },
      {
        id: "bf-013",
        name: "Club Sandwich & Fries",
        description:
          "Eggs, Cheese, Tomato, Lettuce, Cucumber, Shredded Chicken, Bread served with fries",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "bf-014",
        name: "Stir fry Noodles",
        description: "Served with veggies and choice of eggs",
        priceNGN: 8500,
        isActive: true,
      },
    ],
  },
  {
    id: "lunch-dinner-001",
    name: "Lunch & Dinner",
    timing:
      "LUNCH: 12:00 NOON - 6:00 PM DAILY | DINNER: 7:00 PM - 10:00 PM DAILY",
    note: "Lunch is served À La Carte. Dinner is either a buffet or à la carte when the buffet isn't available.",
    isActive: true,
    items: [
      {
        id: "ld-001",
        name: "Abula",
        description:
          "Gbegiri, Ewedu and Buka Stew served with Amala and a choice of Ogufe|Assorted meat|beef|Dry fish",
        priceNGN: 11000,
        isActive: true,
      },
      {
        id: "ld-002",
        name: "Egusi Soup",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-003",
        name: "Ogbono Soup",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-004",
        name: "Efo-riro soup",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-005",
        name: "Edikang Ikong",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-006",
        name: "Afang Soup",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 12500,
        isActive: true,
      },
      {
        id: "ld-007",
        name: "Oha soup",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 12500,
        isActive: true,
      },
      {
        id: "ld-008",
        name: "Bitterleaf soup",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 12500,
        isActive: true,
      },
      {
        id: "ld-009",
        name: "Premium Soups (with Turkey or Snail)",
        description:
          "Egusi, Afang, Ogbono, Oha, Bitterleaf, Edikang Ikong or Eforiro soup served with Eba, Semovita, Poundo Yam, or Wheat and turkey",
        priceNGN: 15000,
        isActive: true,
      },
      {
        id: "ld-010",
        name: "Seafood Okro",
        description: "Served with Eba, Semovita, Poundo Yam or Wheat",
        priceNGN: 20000,
        isActive: true,
      },
      {
        id: "ld-011",
        name: "Whole Fish",
        description:
          "Whole grilled fish served with Rice/Fries/Potato Wedges/Bole and Green Salad",
        priceNGN: 15000,
        isActive: true,
      },
      {
        id: "ld-012",
        name: "Spicy Beans",
        description: "Served with Fried Plantain and Chicken/Beef/Fish",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "ld-013",
        name: "Chicken Cordon Bleu",
        description:
          "Chicken cutlets, Swiss Cheese, Steamed veggies, Potatoes your way & Cordon Bleu sauce",
        priceNGN: 13000,
        isActive: true,
      },
      {
        id: "ld-014",
        name: "Singapore Noodles",
        description: "Served with veggies and Chicken fillet",
        priceNGN: 11000,
        isActive: true,
      },
      {
        id: "ld-015",
        name: "Bolognese Pasta",
        description: "Mixed meat,Onions,Garlic,Tomatoes Sauce, Cheese",
        priceNGN: 12000,
        isActive: true,
      },
      {
        id: "ld-016",
        name: "Chicken and Chips",
        description: "Served with steamed veggies and chilli sauce",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-017",
        name: "Fish & Chips",
        description: "Fish fillet in batter served with tartar sauce and fries",
        priceNGN: 12000,
        isActive: true,
      },
      {
        id: "ld-018",
        name: "Obe Ata Din Din (Pepper Stew)",
        description:
          "Served with White rice, choice of chicken, beef or fish and plantain/Coleslaw",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-019",
        name: "White Rice",
        description:
          "Served with stew and Peppered Grilled Chicken/Beef/Fish/Goat meat and Plantain/Coleslaw",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-020",
        name: "Ofada Rice",
        description: "Served with assorted meat and boiled eggs",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-021",
        name: "Ziba Jollof Rice",
        description:
          "Served with Peppered Grilled Chicken/Beef/Fish/Goat meat and Plantain/Coleslaw",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-022",
        name: "Coconut Rice",
        description:
          "Served with Peppered Grilled Chicken/Beef/Fish/Goat meat and Plantain/Coleslaw",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-023",
        name: "Gizdodo",
        description: "Served with rice of choice",
        priceNGN: 11500,
        isActive: true,
      },
      {
        id: "ld-024",
        name: "Seafood Native Rice",
        description:
          "Smoky, flavourful native rice with prawns, calamari, and smoked fish",
        priceNGN: 14500,
        isActive: true,
      },
      {
        id: "ld-025",
        name: "Premium Rice (with Turkey)",
        description: "White, Jollof or Coconut Rice served with Turkey",
        priceNGN: 15000,
        isActive: true,
      },
      {
        id: "ld-026",
        name: "Asun Wrap",
        description:
          "Spicy and delicious Asun encased in flatbread and served with fries",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "ld-027",
        name: "Ziba Salad",
        description:
          "Lettuce, fresh tomatoes, carrots, eggs, cheddar, swiss cheese, honey, dijon mustard, salt and pepper, olive oil",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "ld-028",
        name: "Pepper soup Bowl",
        description:
          "Assorted/Goat Meat/Cow leg/Chicken Pepper Soup Served with Boiled Yam Cubes",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "ld-029",
        name: "Braised Chicken",
        description:
          "Served with Rice, Buttery garlic green beans, lemon glazed carrots",
        priceNGN: 13500,
        isActive: true,
      },
      {
        id: "ld-030",
        name: "Fish Curry",
        description: "Served with White rice and dried fruits/nuts",
        priceNGN: 12700,
        isActive: true,
      },
      {
        id: "ld-031",
        name: "Beef Carbonate",
        description:
          "Served with Rice|Choice of potatoes and veggies flavored with Beer",
        priceNGN: 12700,
        isActive: true,
      },
      {
        id: "ld-032",
        name: "Chinese Corn soup",
        description:
          "Chicken fillet, Sweetcorn, Egg, Cornflour served with Breadroll",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "ld-033",
        name: "French Onion Soup",
        description: "Served with garlic Bread",
        priceNGN: 8500,
        isActive: true,
      },
      {
        id: "ld-034",
        name: "Cream of Tomato Soup",
        description: "Garnished with crouton. Served with breadroll",
        priceNGN: 8500,
        isActive: true,
      },
      {
        id: "ld-035",
        name: "Stir fry Spaghetti",
        description: "Served with choice of protein",
        priceNGN: 12000,
        isActive: true,
      },
      {
        id: "ld-036",
        name: "Jollof Pasta",
        description:
          "Spaghetti cooked in rich, spicy jollof sauce and herbs served with Chicken/Beef/Assorted meat/Fish",
        priceNGN: 12000,
        isActive: true,
      },
      {
        id: "ld-037",
        name: "Sea food Pasta",
        description:
          "Spaghetti in Fish, Calamari, Shrimps, Onion Garlic, Ginger, Cheese, Tomatoes/Creamy Sauce",
        priceNGN: 15000,
        isActive: true,
      },
      {
        id: "ld-038",
        name: "Wings",
        description:
          "Grilled Barbecue/Chilli/Honey Mustard Wings served with French Fries/Sweet Potato Wedges",
        priceNGN: 9750,
        isActive: true,
      },
      {
        id: "ld-039",
        name: "Chicken Tacos",
        description:
          "Pulled chicken tortilla, bell pepper, avocado mousse, tomato, cheese, onion, sour cream served with fries",
        priceNGN: 12500,
        isActive: true,
      },
      {
        id: "ld-040",
        name: "Beef Tacos",
        description:
          "Beef tortilla, bell pepper, avocado mousse, tomato, cheese, onion, sour cream served with fries",
        priceNGN: 14000,
        isActive: true,
      },
      {
        id: "ld-041",
        name: "Caesar Salad",
        description:
          "Lettuce, tomatoes, cucumber, parmesan cheese, crisp croutons",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "ld-042",
        name: "Beach side Salad",
        description:
          "Cucumbers, Tomatoes, Bell Pepper, Onions, Olives, Feta Cheese, Olive oil",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "ld-043",
        name: "Fruit Salad",
        description:
          "Apples, mango(seasonal), grapes, oranges, pineapples, watermelon, lemon, honey",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "ld-044",
        name: "Summer side Salad",
        description: "Mixed Fruits, Ice cream, Cookies",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "ld-045",
        name: "Pizza",
        description:
          "Your Choice of Margarita, Seafood, Barbecue Chicken or Goat Suya served with Sauté Mixed Vegetables",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "ld-046",
        name: "Isi-Ewu",
        description:
          "Spicy, saucy goat head tossed in rich palm oil and native spices, topped with onions and Utazi leaves.",
        priceNGN: 15000,
        isActive: true,
      },
    ],
  },
  {
    id: "kids-menu-001",
    name: "Kids Menu",
    timing: "10:00 AM – 6:00 PM DAILY",
    note: "Kids meals are typically half the portion of our regular meal size",
    isActive: true,
    items: [
      {
        id: "kids-001",
        name: "Chicken Lolipop",
        description:
          "Chicken wings in Lolipop shape, Egg, Flour, Crumbs, served with fries and ketchup",
        priceNGN: 7200,
        isActive: true,
      },
      {
        id: "kids-002",
        name: "Chicken Nugget",
        description:
          "Chicken fillet, Crumbs, Flour, Egg served with fries and ketchup",
        priceNGN: 8000,
        isActive: true,
      },
      {
        id: "kids-003",
        name: "Hotdog",
        description: "Served with fries and Ketchup",
        priceNGN: 7000,
        isActive: true,
      },
      {
        id: "kids-004",
        name: "Mini Burger",
        description:
          "Beef/Chicken patee, Cocktail sauce, Veggies, Cheese served with fries and ketchup",
        priceNGN: 8500,
        isActive: true,
      },
      {
        id: "kids-005",
        name: "Singapore Noodles",
        description:
          "Veggies, Chicken fillet, Garlic and Ginger, Tumeric, Oyster",
        priceNGN: 7000,
        isActive: true,
      },
      {
        id: "kids-006",
        name: "Stir-fry noodles",
        description: "Served with veggies and choice of eggs",
        priceNGN: 4000,
        isActive: true,
      },
      {
        id: "kids-007",
        name: "Coconut Rice",
        description: "Served with fish strips",
        priceNGN: 7000,
        isActive: true,
      },
    ],
  },
  {
    id: "vegetarian-001",
    name: "Vegetarian",
    timing: "10:00 AM – 6:00 PM DAILY",
    note: "",
    isActive: true,
    items: [
      {
        id: "veg-001",
        name: "Vegetable Curry with Steamed Basmati Rice",
        description:
          "Mixed vegetables simmered in rich curry sauce, served with fluffy basmati rice.",
        priceNGN: 12500,
        isActive: true,
      },
      {
        id: "veg-002",
        name: "Spaghetti with Vegetable Bolognese",
        description:
          "Spaghetti served with a hearty vegetable-packed Bolognese sauce.",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "veg-003",
        name: "Tomato and Zucchini Pasta",
        description:
          "Pasta tossed in fresh tomato sauce with zucchini, garlic, and herbs.",
        priceNGN: 8000,
        isActive: true,
      },
      {
        id: "veg-004",
        name: "Vegetarian Okro",
        description: "Okro, bell peppers, and mushroom with Poundo",
        priceNGN: 12500,
        isActive: true,
      },
      {
        id: "veg-005",
        name: "Vegetarian Rice Plate",
        description:
          "Eggs Your Way (Boiled/Sunny Side Up/Plain Omelet) served with your choice of Jollof Rice or Coconut Rice and Plantain/Green Salad/BBQ Beans",
        priceNGN: 7300,
        isActive: true,
      },
      {
        id: "veg-006",
        name: "Margarita Pizza",
        description: "Classic vegetarian pizza",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "veg-007",
        name: "Mushroom and Scallion",
        description: "Sautéed mushrooms and scallions",
        priceNGN: 6500,
        isActive: true,
      },
      {
        id: "veg-008",
        name: "Chilli Garlic Mushroom Sliders with Fries",
        description:
          "Crispy mushroom sliders with chilli garlic sauce and fries",
        priceNGN: 7800,
        isActive: true,
      },
      {
        id: "veg-009",
        name: "Stir-fried noodles with Mixed Veggies",
        description: "Noodles tossed with assorted fresh vegetables",
        priceNGN: 7300,
        isActive: true,
      },
    ],
  },
  {
    id: "jolly-menu-001",
    name: "Jolly Menu",
    timing: "OPEN DAILY",
    note: "This jolly menu is paid for and not covered in any room booking.",
    isActive: true,
    items: [
      {
        id: "jolly-001",
        name: "Quick Bites",
        description:
          "Pepper Gizzard or Snail served with potato or Yam wedges and chili pepper sauce",
        priceNGN: 18000,
        isActive: true,
      },
      {
        id: "jolly-002",
        name: "Beef Fiesta",
        description:
          "Tender, juicy beef chunks stir-fried in sauce, wrapped in soft flatbread and served with fries.",
        priceNGN: 20000,
        isActive: true,
      },
      {
        id: "jolly-003",
        name: "Grilled Jumbo Prawns",
        description:
          "Served with a side of mashed potatoes/Fries/Rice and steamed veggies",
        priceNGN: 25000,
        isActive: true,
      },
      {
        id: "jolly-004",
        name: "Grilled Lamb Chops",
        description:
          "Served with a side of mashed potatoes/Fries/Rice and steamed veggies",
        priceNGN: 25000,
        isActive: true,
      },
      {
        id: "jolly-005",
        name: "T-bone Steak",
        description:
          "Served with a side of mashed potatoes/Fries/Rice and steamed veggies",
        priceNGN: 25000,
        isActive: true,
      },
      {
        id: "jolly-006",
        name: "Assorted Box (Serves 3)",
        description:
          "Beef suya, Chicken in batter, Chicken Lolipop, Pepper Gizzard, Puff-Puff, Samosa, Spring rolls, Yam Chips served with green vegetable salad",
        priceNGN: 50000,
        isActive: true,
      },
      {
        id: "jolly-007",
        name: "Seafood Box (Serves 3)",
        description:
          "Prawns, Calamari, Fish, Snail, and Crab served with Chili and Tartar sauce with Lemon wedges, Green salad and creamy sauce",
        priceNGN: 60000,
        isActive: true,
      },
    ],
  },
  {
    id: "daypass-001",
    name: "Day Pass Ticket Plus",
    timing: "10:00 AM – 6:00 PM DAILY",
    note: "Select one complimentary meal from the menu below with your Ticket Plus+ purchase",
    isActive: true,
    items: [
      {
        id: "daypass-001",
        name: "Coconut Rice",
        description:
          "Served with Peppered Grilled Chicken or Beef or fish and Plantain/Green Salad",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-002",
        name: "Ziba Jollof Rice",
        description:
          "Served with Chicken|Grilled Fish or Beef and Plantain/Coleslaw",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-003",
        name: "Obe Ata Din Din (Pepper Stew)",
        description: "Served with White rice, protein of choice and plantain",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-004",
        name: "Chicken Sharwama",
        description: "Served with French Fries/Yam Fries/Sweet Potato Fries",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-005",
        name: "Egusi/Ogbono/Efo-riro",
        description:
          "Served with Eba, Semovita, Poundo Yam, or Wheat and a choice of protein Dry fish|Assorted Meat|Goatmeat|Cowleg|Beef|Chicken",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-006",
        name: "Abula",
        description:
          "Gbegiri, Ewedu and Buka Stew served with Amala and a choice of Ogufe|Assorted meat|beef|Dry fish",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-007",
        name: "Bolognese Pasta",
        description: "Mixed meat, Onions, Garlic, Tomatoes Sauce, Cheese",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-008",
        name: "Noodles",
        description: "Served with veggies and choice of eggs",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-009",
        name: "Fish & Chips",
        description: "Fish fillet in batter served with tartar sauce and fries",
        priceNGN: 0,
        isActive: true,
      },
      {
        id: "daypass-010",
        name: "Wings",
        description:
          "Grilled Barbecue/Chilli/Honey Mustard Wings served with French Fries/Sweet Potato Wedges",
        priceNGN: 0,
        isActive: true,
      },
    ],
  },
  {
    id: "non-alcoholic-drinks-001",
    name: "Non-Alcoholic Drinks",
    timing: "AVAILABLE DAILY",
    note: "Soft Drinks, Hot Beverage/Coffee, Milkshakes, Fresh Juice, Mocktails",
    isActive: true,
    items: [
      {
        id: "noalc-001",
        name: "COCA COLA",
        description: "Soft Drink",
        priceNGN: 1500,
        isActive: true,
      },
      {
        id: "noalc-002",
        name: "TONIC WATER",
        description: "Soft Drink",
        priceNGN: 2000,
        isActive: true,
      },
      {
        id: "noalc-003",
        name: "SODA WATER",
        description: "Soft Drink",
        priceNGN: 1500,
        isActive: true,
      },
      {
        id: "noalc-004",
        name: "MALT",
        description: "Soft Drink",
        priceNGN: 2000,
        isActive: true,
      },
      {
        id: "noalc-005",
        name: "FAYROUZ",
        description: "Soft Drink",
        priceNGN: 2000,
        isActive: true,
      },
      {
        id: "noalc-006",
        name: "YOGHURT",
        description: "Soft Drink",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "noalc-007",
        name: "GLASS OF PACK JUICE",
        description: "Fresh Juice",
        priceNGN: 2000,
        isActive: true,
      },
      {
        id: "noalc-008",
        name: "PITCHER OF PACK JUICE",
        description: "Fresh Juice",
        priceNGN: 6000,
        isActive: true,
      },
      {
        id: "noalc-009",
        name: "GLASS OF CRANBERRY JUICE",
        description: "Fresh Juice",
        priceNGN: 7000,
        isActive: true,
      },
      {
        id: "noalc-010",
        name: "PACK OF CRANBERRY JUICE",
        description: "Fresh Juice",
        priceNGN: 15000,
        isActive: true,
      },
      {
        id: "noalc-011",
        name: "SCHWEPPES MOJITO",
        description: "Soft Drink",
        priceNGN: 2000,
        isActive: true,
      },
      {
        id: "noalc-012",
        name: "ORANGE",
        description: "Fresh Juice",
        priceNGN: 6000,
        isActive: true,
      },
      {
        id: "noalc-013",
        name: "WATERMELON",
        description: "Fresh Juice",
        priceNGN: 6000,
        isActive: true,
      },
      {
        id: "noalc-014",
        name: "PINEAPPLE",
        description: "Fresh Juice",
        priceNGN: 6000,
        isActive: true,
      },
      {
        id: "noalc-015",
        name: "PINEAPPLE & GINGER",
        description: "Fresh Juice",
        priceNGN: 6500,
        isActive: true,
      },
      {
        id: "noalc-016",
        name: "BLACK COFFEE",
        description: "Hot Beverage/Coffee",
        priceNGN: 2500,
        isActive: true,
      },
      {
        id: "noalc-017",
        name: "TEA/HOT CHOCOLATE",
        description: "Hot Beverage/Coffee",
        priceNGN: 2500,
        isActive: true,
      },
      {
        id: "noalc-018",
        name: "EXPRESSO/LATTE COFFEE",
        description: "Hot Beverage/Coffee",
        priceNGN: 3000,
        isActive: true,
      },
      {
        id: "noalc-019",
        name: "CAPPUCCINO/AMERICANO",
        description: "Hot Beverage/Coffee",
        priceNGN: 3000,
        isActive: true,
      },
      {
        id: "noalc-020",
        name: "VANILLA",
        description: "Milkshake",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "noalc-021",
        name: "STRAWBERRY",
        description: "Milkshake",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "noalc-022",
        name: "CHOCOLATE",
        description: "Milkshake",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "noalc-023",
        name: "CHAPMAN",
        description: "Mocktail",
        priceNGN: 8700,
        isActive: true,
      },
      {
        id: "noalc-024",
        name: "FRUIT PUNCH",
        description: "Mocktail",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "noalc-025",
        name: "VIRGIN COLADA",
        description: "Mocktail",
        priceNGN: 9500,
        isActive: true,
      },
      {
        id: "noalc-026",
        name: "VIRGIN SUNRISE",
        description: "Mocktail",
        priceNGN: 9700,
        isActive: true,
      },
      {
        id: "noalc-027",
        name: "VIRGIN MOJITO",
        description: "Mocktail",
        priceNGN: 9000,
        isActive: true,
      },
      {
        id: "noalc-028",
        name: "VIRGIN DAIQUIRI",
        description: "Mocktail",
        priceNGN: 9700,
        isActive: true,
      },
    ],
  },
  {
    id: "alcoholic-beer-cocktails-001",
    name: "Alcoholic Drinks - Beer & Cocktails",
    timing: "AVAILABLE DAILY",
    note: "Beer, Shots, Cocktails",
    isActive: true,
    items: [
      {
        id: "alc1-001",
        name: "HEINEKEN",
        description: "Beer",
        priceNGN: 3000,
        isActive: true,
      },
      {
        id: "alc1-002",
        name: "BUDWEISER",
        description: "Beer",
        priceNGN: 3000,
        isActive: true,
      },
      {
        id: "alc1-003",
        name: "SMIRNOFF ICE",
        description: "Beer",
        priceNGN: 4000,
        isActive: true,
      },
      {
        id: "alc1-004",
        name: "STAR RADLER",
        description: "Beer",
        priceNGN: 3000,
        isActive: true,
      },
      {
        id: "alc1-005",
        name: "GUINNESS STOUT",
        description: "Beer",
        priceNGN: 4000,
        isActive: true,
      },
      {
        id: "alc1-006",
        name: "GORDON GIN",
        description: "Shots",
        priceNGN: 3000,
        isActive: true,
      },
      {
        id: "alc1-007",
        name: "SIERRA TEQUILA",
        description: "Shots",
        priceNGN: 3000,
        isActive: true,
      },
      {
        id: "alc1-008",
        name: "OLEMCA TEQUILA",
        description: "Shots",
        priceNGN: 4000,
        isActive: true,
      },
      {
        id: "alc1-009",
        name: "ABSOLUT VODKA",
        description: "Shots",
        priceNGN: 4000,
        isActive: true,
      },
      {
        id: "alc1-010",
        name: "JACK DANIEL",
        description: "Shots",
        priceNGN: 5000,
        isActive: true,
      },
      {
        id: "alc1-011",
        name: "SEX ON THE BEACH",
        description: "Vodka, Peach, Cranberry",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "alc1-012",
        name: "PINA COLADA",
        description: "White rum, Pineapple",
        priceNGN: 9300,
        isActive: true,
      },
      {
        id: "alc1-013",
        name: "LONG ISLAND TEA",
        description: "Rum, Vodka, Tequila, triple sec, Lemon Juice coke",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "alc1-014",
        name: "BLUE OCEAN",
        description: "Rum, Pineapple, cream and Coconut Syrup",
        priceNGN: 9500,
        isActive: true,
      },
      {
        id: "alc1-015",
        name: "SUMMER TREE",
        description: "Vodka, Orange & Pineapple Juice",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "alc1-016",
        name: "PINEAPPLE LONG ISLAND",
        description:
          "Pineapple, Vodka, Gin, Tequila, rum, Triple Sec, lemon juice",
        priceNGN: 10200,
        isActive: true,
      },
      {
        id: "alc1-017",
        name: "BLOODY MOON",
        description: "White rum, Orange Syrup",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "alc1-018",
        name: "MOJITO",
        description: "White rum, Syrup, Mint leaves",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "alc1-019",
        name: "NANA DAIQUIRI",
        description: "Rum, Cream & Syrup",
        priceNGN: 10000,
        isActive: true,
      },
      {
        id: "alc1-020",
        name: "COSMOPLITAN",
        description: "Vodka, Lime Juice, Syrup Cranberry juice",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "alc1-021",
        name: "FROZEN DAIQUIRI",
        description: "Rum, Strawberry, lemon",
        priceNGN: 9500,
        isActive: true,
      },
      {
        id: "alc1-022",
        name: "CLASSIC MAGARITA",
        description: "Vodka, Lime Juice, Syrup",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "alc1-023",
        name: "FLAVOURED MAGRITA",
        description: "Vodka, Lemon Juice, Cranberry juice",
        priceNGN: 9800,
        isActive: true,
      },
      {
        id: "alc1-024",
        name: "CLASSIC DAIQUIRI",
        description: "Rum, Lemon Juice, Syrup",
        priceNGN: 9500,
        isActive: true,
      },
      {
        id: "alc1-025",
        name: "TEQUILA SUNRISE",
        description: "Vodka, Orange Juice",
        priceNGN: 10200,
        isActive: true,
      },
      {
        id: "alc1-026",
        name: "FLAVOURED DAIQUIRI",
        description:
          "Rum, Lemon Juice, Coconut, Peach, Strawberry, Vanilla Syrup",
        priceNGN: 10500,
        isActive: true,
      },
      {
        id: "alc1-027",
        name: "MAD CONNECTION",
        description: "Rum, Gin, Vodka",
        priceNGN: 10500,
        isActive: true,
      },
    ],
  },
  {
    id: "alcoholic-wine-spirits-001",
    name: "Alcoholic Drinks - Wine & Spirits",
    timing: "AVAILABLE DAILY",
    note: "Wine, Whisky, Vodka, Cognac/Liquor",
    isActive: true,
    items: [
      {
        id: "alc2-001",
        name: "CARLO ROSSI",
        description: "Wine",
        priceNGN: 35000,
        isActive: true,
      },
      {
        id: "alc2-002",
        name: "FOUR COUSIN",
        description: "Wine",
        priceNGN: 35000,
        isActive: true,
      },
      {
        id: "alc2-003",
        name: "4TH STREET",
        description: "Wine",
        priceNGN: 32500,
        isActive: true,
      },
      {
        id: "alc2-004",
        name: "CHAMDOR",
        description: "Wine",
        priceNGN: 30000,
        isActive: true,
      },
      {
        id: "alc2-005",
        name: "DECLAN",
        description: "Wine",
        priceNGN: 33500,
        isActive: true,
      },
      {
        id: "alc2-006",
        name: "OCEAN BEACH",
        description: "Wine",
        priceNGN: 33500,
        isActive: true,
      },
      {
        id: "alc2-007",
        name: "ASCONI AGOR",
        description: "Wine",
        priceNGN: 45000,
        isActive: true,
      },
      {
        id: "alc2-008",
        name: "ESCUDO ROJO",
        description: "Wine",
        priceNGN: 60000,
        isActive: true,
      },
      {
        id: "alc2-009",
        name: "ANDRE ROSE",
        description: "Wine",
        priceNGN: 45000,
        isActive: true,
      },
      {
        id: "alc2-010",
        name: "ANDRE BRUT",
        description: "Wine",
        priceNGN: 50000,
        isActive: true,
      },
      {
        id: "alc2-011",
        name: "MOET & CHANDOR ROSE",
        description: "Wine",
        priceNGN: 216000,
        isActive: true,
      },
      {
        id: "alc2-012",
        name: "MOET BRUT",
        description: "Wine",
        priceNGN: 240000,
        isActive: true,
      },
      {
        id: "alc2-013",
        name: "MOET ROSE",
        description: "Wine",
        priceNGN: 240000,
        isActive: true,
      },
      {
        id: "alc2-014",
        name: "VEUVE-CLIQOUT",
        description: "Wine",
        priceNGN: 290000,
        isActive: true,
      },
      {
        id: "alc2-015",
        name: "GIOVANI ROSE",
        description: "Wine",
        priceNGN: 100000,
        isActive: true,
      },
      {
        id: "alc2-016",
        name: "MARTINI ROSE",
        description: "Wine",
        priceNGN: 40350,
        isActive: true,
      },
      {
        id: "alc2-017",
        name: "BOMBAY SHAPHIRE",
        description: "Vodka",
        priceNGN: 65000,
        isActive: true,
      },
      {
        id: "alc2-018",
        name: "ABSOLUT VODKA",
        description: "Vodka",
        priceNGN: 46500,
        isActive: true,
      },
      {
        id: "alc2-019",
        name: "OLMECA TEQUILA",
        description: "Vodka",
        priceNGN: 60000,
        isActive: true,
      },
      {
        id: "alc2-020",
        name: "SIERRA TEQUILA",
        description: "Vodka",
        priceNGN: 35500,
        isActive: true,
      },
      {
        id: "alc2-021",
        name: "BACARDI WHITE",
        description: "Vodka",
        priceNGN: 46800,
        isActive: true,
      },
      {
        id: "alc2-022",
        name: "BACARDI GOLD",
        description: "Vodka",
        priceNGN: 44500,
        isActive: true,
      },
      {
        id: "alc2-023",
        name: "GORDON GIN",
        description: "Vodka",
        priceNGN: 25000,
        isActive: true,
      },
      {
        id: "alc2-024",
        name: "RED LABEL",
        description: "Whisky",
        priceNGN: 70000,
        isActive: true,
      },
      {
        id: "alc2-025",
        name: "BLACK LABEL",
        description: "Whisky",
        priceNGN: 76000,
        isActive: true,
      },
      {
        id: "alc2-026",
        name: "JACK DANIEL",
        description: "Whisky",
        priceNGN: 76000,
        isActive: true,
      },
      {
        id: "alc2-027",
        name: "WILLIAM LAWSON",
        description: "Whisky",
        priceNGN: 50000,
        isActive: true,
      },
      {
        id: "alc2-028",
        name: "BALLANTINE",
        description: "Whisky",
        priceNGN: 40500,
        isActive: true,
      },
      {
        id: "alc2-029",
        name: "WILD TURKEY",
        description: "Whisky",
        priceNGN: 75000,
        isActive: true,
      },
      {
        id: "alc2-030",
        name: "GLENFIDDICH 18 YRS",
        description: "Whisky",
        priceNGN: 265000,
        isActive: true,
      },
      {
        id: "alc2-031",
        name: "JAMESON BLACK",
        description: "Whisky",
        priceNGN: 100000,
        isActive: true,
      },
      {
        id: "alc2-032",
        name: "JAMESON IRISH",
        description: "Whisky",
        priceNGN: 78500,
        isActive: true,
      },
      {
        id: "alc2-033",
        name: "HENNESSY VS",
        description: "Cognac/Liquor",
        priceNGN: 168000,
        isActive: true,
      },
      {
        id: "alc2-034",
        name: "HENESSY VSOP",
        description: "Cognac/Liquor",
        priceNGN: 216000,
        isActive: true,
      },
      {
        id: "alc2-035",
        name: "MARTEL VS",
        description: "Cognac/Liquor",
        priceNGN: 150000,
        isActive: true,
      },
      {
        id: "alc2-036",
        name: "MARTEL BLUESWIFT",
        description: "Cognac/Liquor",
        priceNGN: 210000,
        isActive: true,
      },
      {
        id: "alc2-037",
        name: "BAILEYS ORIGINAL",
        description: "Cognac/Liquor",
        priceNGN: 54000,
        isActive: true,
      },
      {
        id: "alc2-038",
        name: "CAMPARI BIG",
        description: "Cognac/Liquor",
        priceNGN: 45000,
        isActive: true,
      },
    ],
  },
];
