-- Direct SQL seeding - paste this into Supabase SQL Editor
-- This bypasses schema cache issues and inserts all 121 menu items

INSERT INTO menus (id, categoryId, itemId, category, name, description, price, available) VALUES
-- BREAKFAST
('bf-001', 'breakfast', 'bf-001', 'Breakfast', 'Toast Bread', 'Toast bread and omelette served with choice of Tea/Coffee/Hot chocolate', 9000, true),
('bf-002', 'breakfast', 'bf-002', 'Breakfast', 'Full English Breakfast', 'Bread Basket, Baked beans, Steamed carrots, potatoes, Grilled sausage, Eggs your way, choice of Oatmeal|Cornflakes|Custard and choice of Tea|Coffee|Hot Chocolate', 10500, true),
('bf-003', 'breakfast', 'bf-003', 'Breakfast', 'American Breakfast', 'Pancakes, Potatoes served with Bacon or sausage, Eggs your way and choice of Tea|Coffee|Hot Chocolate', 10500, true),
('bf-004', 'breakfast', 'bf-004', 'Breakfast', 'Tubers N Sauces', 'Boiled or fried Yam served with your choice of Egg Sauce/Fish Sauce/Vegetable Sauce', 8300, true),
('bf-005', 'breakfast', 'bf-005', 'Breakfast', 'Plantain n Vegetable Sauce', 'Plantain how you like it [Boiled, fried or grilled] with Ziba vegetable sauce', 8300, true),
('bf-006', 'breakfast', 'bf-006', 'Breakfast', 'Naija Breakfast', 'Akara & Pap', 8500, true),
('bf-007', 'breakfast', 'bf-007', 'Breakfast', 'Oat Bowl', 'Served with boiled Eggs, Nuts, Coconut flakes, Honey and dates', 10000, true),
('bf-008', 'breakfast', 'bf-008', 'Breakfast', 'Yoghurt Bowl', 'Greek Yoghurt served with granola, chia seeds, coconut flakes and fruit of choice', 10000, true),
('bf-009', 'breakfast', 'bf-009', 'Breakfast', 'French Toast', 'Served with Egg, cinnamon powder, sausage and baked beans', 9000, true),
('bf-010', 'breakfast', 'bf-010', 'Breakfast', 'Yamarita Special', 'Served with Vegetable or Fish sauce', 9000, true),
('bf-011', 'breakfast', 'bf-011', 'Breakfast', 'Potato Fiesta', 'Grilled or Fried sweet Potato served with Egg or Fish sauce', 9300, true),
('bf-012', 'breakfast', 'bf-012', 'Breakfast', 'Plain Homemade Pancake', 'Served with syrup, scrambled eggs and sausage', 7750, true),
('bf-013', 'breakfast', 'bf-013', 'Breakfast', 'Club Sandwich & Fries', 'Eggs, Cheese, Tomato, Lettuce, Cucumber, Shredded Chicken, Bread served with fries', 10000, true),
('bf-014', 'breakfast', 'bf-014', 'Breakfast', 'Stir fry Noodles', 'Served with veggies and choice of eggs', 8500, true),
-- LUNCH/DINNER
('ld-001', 'lunch-dinner', 'ld-001', 'Lunch/Dinner', 'Abula', 'Gbegiri, Ewedu and Buka Stew served with Amala and choice of Ogufe|Assorted meat|beef|Dry fish', 11000, true),
('ld-002', 'lunch-dinner', 'ld-002', 'Lunch/Dinner', 'Egusi Soup', 'Served with Eba, Semovita, Poundo Yam or Wheat and choice of protein', 11500, true),
('ld-003', 'lunch-dinner', 'ld-003', 'Lunch/Dinner', 'Ogbono Soup', 'Served with Eba, Semovita, Poundo Yam or Wheat and choice of protein', 11500, true),
('ld-004', 'lunch-dinner', 'ld-004', 'Lunch/Dinner', 'Efo-riro Soup', 'Served with Eba, Semovita, Poundo Yam or Wheat and choice of protein', 11500, true),
('ld-005', 'lunch-dinner', 'ld-005', 'Lunch/Dinner', 'Edikang Ikong', 'Served with Eba, Semovita, Poundo Yam or Wheat and choice of protein', 11500, true),
('ld-006', 'lunch-dinner', 'ld-006', 'Lunch/Dinner', 'Afang Soup', 'Served with Eba, Semovita, Poundo Yam or Wheat and choice of protein', 12500, true),
('ld-007', 'lunch-dinner', 'ld-007', 'Lunch/Dinner', 'Oha Soup', 'Served with Eba, Semovita, Poundo Yam or Wheat and choice of protein', 12500, true),
('ld-008', 'lunch-dinner', 'ld-008', 'Lunch/Dinner', 'Bitterleaf Soup', 'Served with Eba, Semovita, Poundo Yam or Wheat and choice of protein', 12500, true),
('ld-009', 'lunch-dinner', 'ld-009', 'Lunch/Dinner', 'Soup with Turkey or Snail', 'Egusi/Afang/Ogbono/Oha/Bitterleaf/Edikang Ikong/Eforiro soup served with Eba or Wheat and turkey', 15000, true),
('ld-010', 'lunch-dinner', 'ld-010', 'Lunch/Dinner', 'Seafood Okro', 'Served with Eba, Semovita, Poundo Yam or Wheat', 20000, true),
('ld-011', 'lunch-dinner', 'ld-011', 'Lunch/Dinner', 'Whole Fish', 'Whole grilled fish served with Rice/Fries/Potato Wedges/Bole and Green Salad', 15000, true),
('ld-012', 'lunch-dinner', 'ld-012', 'Lunch/Dinner', 'Spicy Beans', 'Served with Fried Plantain and Chicken/Beef/Fish', 10500, true),
('ld-013', 'lunch-dinner', 'ld-013', 'Lunch/Dinner', 'Chicken Cordon Bleu', 'Chicken cutlets, Swiss Cheese, Steamed veggies, Potatoes and Cordon Bleu sauce', 13000, true),
('ld-014', 'lunch-dinner', 'ld-014', 'Lunch/Dinner', 'Singapore Noodles', 'Served with veggies and Chicken fillet', 11000, true),
('ld-015', 'lunch-dinner', 'ld-015', 'Lunch/Dinner', 'Bolognese Pasta', 'Mixed meat, Onions, Garlic, Tomatoes Sauce, Cheese', 12000, true),
('ld-016', 'lunch-dinner', 'ld-016', 'Lunch/Dinner', 'Chicken and Chips', 'Served with steamed veggies and chilli sauce', 11500, true),
('ld-017', 'lunch-dinner', 'ld-017', 'Lunch/Dinner', 'Fish & Chips', 'Fish fillet in batter served with tartar sauce and fries', 12000, true),
('ld-018', 'lunch-dinner', 'ld-018', 'Lunch/Dinner', 'Obe Ata Din Din Pepper Stew', 'Served with White rice, choice of chicken/beef/fish and plantain/Coleslaw', 11500, true),
('ld-019', 'lunch-dinner', 'ld-019', 'Lunch/Dinner', 'White Rice', 'Served with stew and Peppered Grilled Chicken/Beef/Fish/Goat meat and Plantain/Coleslaw', 11500, true),
('ld-020', 'lunch-dinner', 'ld-020', 'Lunch/Dinner', 'Ofada Rice', 'Served with assorted meat and boiled eggs', 11500, true),
('ld-021', 'lunch-dinner', 'ld-021', 'Lunch/Dinner', 'Ziba Jollof Rice', 'Served with Peppered Grilled Chicken/Beef/Fish/Goat meat and Plantain/Coleslaw', 11500, true),
('ld-022', 'lunch-dinner', 'ld-022', 'Lunch/Dinner', 'Coconut Rice', 'Served with Peppered Grilled Chicken/Beef/Fish/Goat meat and Plantain/Coleslaw', 11500, true),
('ld-023', 'lunch-dinner', 'ld-023', 'Lunch/Dinner', 'Gizdodo', 'Served with rice of choice', 11500, true),
('ld-024', 'lunch-dinner', 'ld-024', 'Lunch/Dinner', 'Seafood Native Rice', 'Smoky, flavourful native rice with prawns, calamari and smoked fish', 14500, true),
('ld-025', 'lunch-dinner', 'ld-025', 'Lunch/Dinner', 'Rice with Turkey', 'White/Jollof/Coconut Rice served with Turkey', 15000, true),
('ld-026', 'lunch-dinner', 'ld-026', 'Lunch/Dinner', 'Asun Wrap', 'Spicy and delicious Asun encased in flatbread and served with fries', 10500, true),
('ld-027', 'lunch-dinner', 'ld-027', 'Lunch/Dinner', 'Ziba Salad', 'Lettuce, fresh tomatoes, carrots, eggs, cheddar, swiss cheese, honey, dijon mustard, olive oil', 10000, true),
('ld-028', 'lunch-dinner', 'ld-028', 'Lunch/Dinner', 'Pepper Soup Bowl', 'Assorted/Goat Meat/Cow leg/Chicken Pepper Soup served with Boiled Yam Cubes', 10000, true),
('ld-029', 'lunch-dinner', 'ld-029', 'Lunch/Dinner', 'Braised Chicken', 'Served with Rice, Buttery garlic green beans, lemon grazed carrots', 13500, true),
('ld-030', 'lunch-dinner', 'ld-030', 'Lunch/Dinner', 'Fish Curry', 'Served with White rice and dried fruits/nuts', 12700, true),
('ld-031', 'lunch-dinner', 'ld-031', 'Lunch/Dinner', 'Beef Carbonate', 'Served with Rice, choice of potatoes and veggies flavored with Beer', 12700, true),
('ld-032', 'lunch-dinner', 'ld-032', 'Lunch/Dinner', 'Chinese Corn Soup', 'Chicken fillet, Sweetcorn, Egg, Cornflour served with Breadroll', 9000, true),
('ld-033', 'lunch-dinner', 'ld-033', 'Lunch/Dinner', 'French Onion Soup', 'Served with garlic Bread', 8500, true),
('ld-034', 'lunch-dinner', 'ld-034', 'Lunch/Dinner', 'Cream of Tomato Soup', 'Garnished with crouton. Served with breadroll', 8500, true),
('ld-035', 'lunch-dinner', 'ld-035', 'Lunch/Dinner', 'Stir Fry Spaghetti', 'Served with choice of protein', 12000, true),
('ld-036', 'lunch-dinner', 'ld-036', 'Lunch/Dinner', 'Jollof Pasta', 'Spaghetti cooked in rich, spicy jollof sauce with Chicken/Beef/Assorted meat/Fish', 12000, true),
('ld-037', 'lunch-dinner', 'ld-037', 'Lunch/Dinner', 'Seafood Pasta', 'Spaghetti with Fish, Calamari, Shrimps, Onion, Garlic, Ginger, Cheese and Tomato Sauce', 15000, true),
('ld-038', 'lunch-dinner', 'ld-038', 'Lunch/Dinner', 'Wings', 'Grilled Barbecue/Chilli/Honey Mustard Wings served with French Fries/Sweet Potato Wedges', 9750, true),
('ld-039', 'lunch-dinner', 'ld-039', 'Lunch/Dinner', 'Chicken Tacos', 'Pulled chicken tortilla, bell pepper, avocado mousse, tomato, cheese, onion, sour cream with fries', 12500, true),
('ld-040', 'lunch-dinner', 'ld-040', 'Lunch/Dinner', 'Beef Tacos', 'Beef tortilla, bell pepper, avocado mousse, tomato, cheese, onion, sour cream with fries', 14000, true),
('ld-041', 'lunch-dinner', 'ld-041', 'Lunch/Dinner', 'Caesar Salad', 'Lettuce, tomatoes, cucumber, parmesan cheese, crisp croutons', 9000, true),
('ld-042', 'lunch-dinner', 'ld-042', 'Lunch/Dinner', 'Beachside Salad', 'Cucumbers, Tomatoes, Bell Pepper, Onions, Olives, Feta Cheese, Olive oil', 9000, true),
('ld-043', 'lunch-dinner', 'ld-043', 'Lunch/Dinner', 'Fruit Salad', 'Apples, mango (seasonal), grapes, oranges, pineapples, watermelon, lemon, honey', 10000, true),
('ld-044', 'lunch-dinner', 'ld-044', 'Lunch/Dinner', 'Summer Side Salad', 'Mixed Fruits, Ice cream, Cookies', 10000, true),
('ld-045', 'lunch-dinner', 'ld-045', 'Lunch/Dinner', 'Pizza', 'Choice of Margarita, Seafood, Barbecue Chicken or Goat Suya with Sauté Mixed Vegetables', 10000, true),
('ld-046', 'lunch-dinner', 'ld-046', 'Lunch/Dinner', 'Isi-Ewu', 'Spicy, saucy goat head tossed in rich palm oil and native spices, topped with onions and Utazi leaves', 15000, true),
-- KIDS MENU
('km-001', 'kids-menu', 'km-001', 'Kids Menu', 'Chicken Lolipop', 'Chicken wings in Lolipop shape, Egg, Flour, Crumbs, served with fries and ketchup', 7200, true),
('km-002', 'kids-menu', 'km-002', 'Kids Menu', 'Chicken Nugget', 'Chicken fillet, Crumbs, Flour, Egg served with fries and ketchup', 8000, true),
('km-003', 'kids-menu', 'km-003', 'Kids Menu', 'Hotdog', 'Served with fries and Ketchup', 7000, true),
('km-004', 'kids-menu', 'km-004', 'Kids Menu', 'Mini Burger', 'Beef/Chicken patty, Cocktail sauce, Veggies, Cheese served with fries and ketchup', 8500, true),
('km-005', 'kids-menu', 'km-005', 'Kids Menu', 'Singapore Noodles', 'Veggies, Chicken fillet, Garlic and Ginger, Turmeric, Oyster', 7000, true),
('km-006', 'kids-menu', 'km-006', 'Kids Menu', 'Stir-fry Noodles', 'Served with veggies and choice of eggs', 4000, true),
('km-007', 'kids-menu', 'km-007', 'Kids Menu', 'Coconut Rice', 'Served with fish strips', 7000, true),
-- VEGETARIAN
('vg-001', 'vegetarian', 'vg-001', 'Vegetarian', 'Vegetable Curry with Basmati Rice', 'Mixed vegetables simmered in rich curry sauce, served with fluffy basmati rice', 12500, true),
('vg-002', 'vegetarian', 'vg-002', 'Vegetarian', 'Spaghetti with Vegetable Bolognese', 'Spaghetti served with a hearty vegetable-packed Bolognese sauce', 9000, true),
('vg-003', 'vegetarian', 'vg-003', 'Vegetarian', 'Tomato and Zucchini Pasta', 'Pasta tossed in fresh tomato sauce with zucchini, garlic and herbs', 8000, true),
('vg-004', 'vegetarian', 'vg-004', 'Vegetarian', 'Vegetarian Okro with Poundo', 'Okra, bell peppers and mushroom with pounded yam', 12500, true),
('vg-005', 'vegetarian', 'vg-005', 'Vegetarian', 'Vegetarian Rice Plate', 'Served with choice of Jollof Rice or Coconut Rice and Plantain/Green Salad', 7300, true),
('vg-006', 'vegetarian', 'vg-006', 'Vegetarian', 'Eggs Your Way', 'Boiled/Sunny Side Up/Plain Omelet served with Jollof/Coconut Rice and Plantain/Green Salad', 9000, true),
('vg-007', 'vegetarian', 'vg-007', 'Vegetarian', 'Margarita Pizza', 'Classic pizza with fresh tomato and herbs', 10000, true),
('vg-008', 'vegetarian', 'vg-008', 'Vegetarian', 'Mushroom and Scallion', 'Fresh mushroom and scallion with rice or pasta', 6500, true),
('vg-009', 'vegetarian', 'vg-009', 'Vegetarian', 'Chilli Garlic Mushroom Sliders with Fries', 'Mushroom sliders with chilli garlic sauce', 7800, true),
('vg-010', 'vegetarian', 'vg-010', 'Vegetarian', 'Stir-fried Noodles with Veggies', 'Mixed vegetables stir-fried with noodles', 7300, true),
-- JOLLY MENU
('jm-001', 'jolly-menu', 'jm-001', 'Jolly Menu', 'Quick Bites', 'Pepper Gizzard or Snail served with potato or Yam wedges and chili pepper sauce', 18000, true),
('jm-002', 'jolly-menu', 'jm-002', 'Jolly Menu', 'Beef Fiesta', 'Tender, juicy beef chunks stir-fried in sauce, wrapped in soft flatbread and served with fries', 20000, true),
('jm-003', 'jolly-menu', 'jm-003', 'Jolly Menu', 'Grilled Jumbo Prawns', 'Served with mashed potatoes/Fries/Rice and steamed veggies', 25000, true),
('jm-004', 'jolly-menu', 'jm-004', 'Jolly Menu', 'Grilled Lamb Chops', 'Served with mashed potatoes/Fries/Rice and steamed veggies', 25000, true),
('jm-005', 'jolly-menu', 'jm-005', 'Jolly Menu', 'T-bone Steak', 'Served with mashed potatoes/Fries/Rice and steamed veggies', 25000, true),
('jm-006', 'jolly-menu', 'jm-006', 'Jolly Menu', 'Assorted Box (Serves 3)', 'Beef suya, Chicken in batter, Chicken Lolipop, Pepper Gizzard, Samosa, Spring rolls, Yam Chips with salad', 50000, true),
('jm-007', 'jolly-menu', 'jm-007', 'Jolly Menu', 'Seafood Box (Serves 3)', 'Prawns, Calamari, Fish, Snail and Crab with Chili, Tartar sauce and Green salad', 60000, true),
-- DAYPASS MENU
('dp-001', 'daypass-menu', 'dp-001', 'Daypass Menu', 'Coconut Rice', 'Served with Peppered Grilled Chicken/Beef/Fish and Plantain/Green Salad', 0, true),
('dp-002', 'daypass-menu', 'dp-002', 'Daypass Menu', 'Ziba Jollof Rice', 'Served with Chicken/Grilled Fish/Beef and Plantain/Coleslaw', 0, true),
('dp-003', 'daypass-menu', 'dp-003', 'Daypass Menu', 'Obe Ata Din Din', 'Pepper Stew served with White rice, protein of choice and plantain', 0, true),
('dp-004', 'daypass-menu', 'dp-004', 'Daypass Menu', 'Chicken Sharwama', 'Served with French Fries/Yam Fries/Sweet Potato Fries', 0, true),
('dp-005', 'daypass-menu', 'dp-005', 'Daypass Menu', 'Soup with Varieties', 'Egusi/Ogbono/Efo-riro with Eba, Semovita or Wheat and choice of protein', 0, true),
('dp-006', 'daypass-menu', 'dp-006', 'Daypass Menu', 'Abula', 'Gbegiri, Ewedu and Buka Stew with Amala and choice of meat', 0, true),
('dp-007', 'daypass-menu', 'dp-007', 'Daypass Menu', 'Bolognese Pasta', 'Mixed meat, Onions, Garlic, Tomatoes Sauce, Cheese', 0, true),
('dp-008', 'daypass-menu', 'dp-008', 'Daypass Menu', 'Noodles', 'Served with veggies and choice of eggs', 0, true),
('dp-009', 'daypass-menu', 'dp-009', 'Daypass Menu', 'Fish & Chips', 'Fish fillet in batter served with tartar sauce and fries', 0, true),
('dp-010', 'daypass-menu', 'dp-010', 'Daypass Menu', 'Wings', 'Grilled Barbecue/Chilli/Honey Mustard Wings with French Fries', 0, true),
-- SOFT DRINKS
('dr-001', 'soft-drinks', 'dr-001', 'Soft Drinks', 'Coca Cola', 'Cold carbonated soft drink', 1500, true),
('dr-002', 'soft-drinks', 'dr-002', 'Soft Drinks', 'Tonic Water', 'Refreshing tonic water', 2000, true),
('dr-003', 'soft-drinks', 'dr-003', 'Soft Drinks', 'Soda Water', 'Plain carbonated water', 1500, true),
('dr-004', 'soft-drinks', 'dr-004', 'Soft Drinks', 'Malt', 'Non-alcoholic malt beverage', 2000, true),
('dr-005', 'soft-drinks', 'dr-005', 'Soft Drinks', 'Fayrouz', 'Fruity non-alcoholic lager', 2000, true),
('dr-006', 'soft-drinks', 'dr-006', 'Soft Drinks', 'Yoghurt', 'Creamy yoghurt drink', 9000, true),
('dr-007', 'soft-drinks', 'dr-007', 'Soft Drinks', 'Glass of Pack Juice', 'Fresh fruit juice in glass', 2000, true),
('dr-008', 'soft-drinks', 'dr-008', 'Soft Drinks', 'Pitcher of Pack Juice', 'Fresh fruit juice pitcher', 6000, true),
('dr-009', 'soft-drinks', 'dr-009', 'Soft Drinks', 'Glass of Cranberry Juice', 'Fresh cranberry juice in glass', 7000, true),
('dr-010', 'soft-drinks', 'dr-010', 'Soft Drinks', 'Pack of Cranberry Juice', 'Fresh cranberry juice pack', 15000, true),
('dr-011', 'soft-drinks', 'dr-011', 'Soft Drinks', 'Schweppes Mojito', 'Mojito flavored soft drink', 2000, true),
-- FRESH JUICE
('fj-001', 'fresh-juice', 'fj-001', 'Fresh Juice', 'Orange Juice', 'Freshly squeezed orange juice', 6000, true),
('fj-002', 'fresh-juice', 'fj-002', 'Fresh Juice', 'Watermelon Juice', 'Fresh watermelon juice', 6000, true),
('fj-003', 'fresh-juice', 'fj-003', 'Fresh Juice', 'Pineapple Juice', 'Fresh pineapple juice', 6000, true),
('fj-004', 'fresh-juice', 'fj-004', 'Fresh Juice', 'Pineapple & Ginger Juice', 'Fresh pineapple juice with ginger', 6500, true),
-- HOT BEVERAGE
('hb-001', 'hot-beverage', 'hb-001', 'Hot Beverage', 'Black Coffee', 'Rich black coffee', 2500, true),
('hb-002', 'hot-beverage', 'hb-002', 'Hot Beverage', 'Tea/Hot Chocolate', 'Hot tea or chocolate beverage', 2500, true),
('hb-003', 'hot-beverage', 'hb-003', 'Hot Beverage', 'Espresso/Latte Coffee', 'Quality espresso or latte', 3000, true),
('hb-004', 'hot-beverage', 'hb-004', 'Hot Beverage', 'Cappuccino/Americano', 'Italian cappuccino or americano', 3000, true),
-- MILKSHAKES
('ms-001', 'milkshakes', 'ms-001', 'Milkshakes', 'Vanilla Milkshake', 'Creamy vanilla milkshake', 10000, true),
('ms-002', 'milkshakes', 'ms-002', 'Milkshakes', 'Strawberry Milkshake', 'Fresh strawberry milkshake', 10000, true),
('ms-003', 'milkshakes', 'ms-003', 'Milkshakes', 'Chocolate Milkshake', 'Rich chocolate milkshake', 10000, true),
-- MOCKTAILS
('mc-001', 'mocktails', 'mc-001', 'Mocktails', 'Chapman', 'Traditional mixed fruit mocktail', 8700, true),
('mc-002', 'mocktails', 'mc-002', 'Mocktails', 'Fruit Punch', 'Tropical fruit punch', 9000, true),
('mc-003', 'mocktails', 'mc-003', 'Mocktails', 'Virgin Colada', 'Coconut and pineapple mocktail', 9500, true),
('mc-004', 'mocktails', 'mc-004', 'Mocktails', 'Virgin Sunrise', 'Sunrise inspired non-alcoholic drink', 9700, true),
('mc-005', 'mocktails', 'mc-005', 'Mocktails', 'Virgin Mojito', 'Refreshing mint mocktail', 9000, true)
ON CONFLICT (id) DO NOTHING;

-- Verify seeding
SELECT COUNT(*) as total_items, 
       COUNT(DISTINCT category) as categories 
FROM menus;
